title: "Alfonso Meraz"
description: "AI × finance × real estate — building Thesis AI and writing notes along the way."
url: "https://alfonsomeraz.github.io" 
baseurl: "" # e.g., "/myrepo" for project sites


# Theme & plugins supported by GitHub Pages
remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap


# Minima options
minima:
skin: auto # light/dark auto
social_links:
- { platform: github, user_url: "https://github.com/alfonsodmeraz" }
- { platform: linkedin, user_url: "https://www.linkedin.com/in/alfonsodmeraz" }


# Build settings
markdown: kramdown
highlighter: rouge


# Navigation
header_pages:
- about.md
- projects.md
- contact.md


# SEO (jekyll-seo-tag)
logo: /assets/img/site-icon.png # optional


# Collections (optional later)
# collections:
# notes:
# output: true


# Permalinks
permalink: /blog/:title/


# Feed options
feed:
path: feed.xml

